apiVersion: v1
kind: Pod
metadata:
  name: k8s-java-reqs-client-otel
  labels:
    app: k8s-java-reqs-client-otel
spec:
  containers:
  - name: k8s-java-reqs-client-otel
    image: docker.io/stevelsplunk/splk-java:latest
    env:
    - name: OTEL_EXPORTER_JAEGER_SERVICE_NAME
      value: k8s-java-reqs-client-otel
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(MY_NODE_NAME):9080/v1/trace
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: Always
  restartPolicy: Always
