apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: docker.io/stevelsplunk/test-platform
    env:
    - name: TZ
      value: America/New_York
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: Always