apiVersion: v1
kind: Pod
metadata:
  name: k8s-py-test-otel
  labels:
    app: k8s-py-test-otel
spec:
  containers:
  -  name: k8s-py-test-otel
     image: docker.io/stevelsplunk/splk-python:latest
     env:
     - name: SPLK_SERVICE_NAME
       value: k8s-py-test
     - name: MY_NODE_NAME
       valueFrom:
         fieldRef:
           apiVersion: v1
           fieldPath: spec.nodeName
     - name: SPLK_TRACE_EXPORTER_URL
       value: http://$(MY_NODE_NAME):9080/v1/trace
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
     imagePullPolicy: Always
  restartPolicy: Always
