apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-flask-otel
spec:
  selector:
    matchLabels:
      name: server-flask-otel
  template:
    metadata:
      labels:
        name: server-flask-otel
    spec:
      containers:
        - name: server-flask-otel
          image: 'docker.io/stevelsplunk/splk-python:latest'
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: SPLK_SERVICE_NAME
              value: server-flask-otel
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: SPLK_TRACE_EXPORTER_URL
              value: http://$(MY_NODE_NAME):9080/v1/trace
          command:
            - /bin/sh
          args:
            - run-server-otel.sh
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: server-flask-otel
spec:
  selector:
    name: server-flask-otel
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
