### Flask Server Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-flask-otel-k8s
spec:
  selector:
    matchLabels:
      name: server-flask-otel-k8s
  template:
    metadata:
      labels:
        name: server-flask-otel-k8s
    spec:
      containers:
        - name: server-flask-otel-k8s
          image: 'docker.io/stevelsplunk/splk-python:latest'
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: SPLUNK_SERVICE_NAME
              value: server-flask-otel-k8s
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://$(MY_NODE_NAME):9080/v1/trace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment:apm-workshop
          command:
            - /bin/sh
          args:
            - run-server-otel.sh
### Flask Server Service
---
apiVersion: v1
kind: Service
metadata:
  name: server-flask-otel-k8s
spec:
  selector:
    name: server-flask-otel-k8s
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
### Python Requests Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: client-py-otel-k8s
  labels:
    app: client-py-otel-k8s
spec:
  containers:
  - name: client-py-otel-k8s
    image: docker.io/stevelsplunk/splk-python:latest
    env:
    - name: SPLUNK_SERVICE_NAME
      value: client-py-otel-k8s
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(MY_NODE_NAME):9080/v1/trace
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment:apm-workshop
    command: ["/bin/sh"]
    args: ["run-client-k8s-otel.sh"]