apiVersion: v1
kind: Pod
metadata:
  name: python-requests-autogen
  labels:
    app: python-requests-autogen
spec:
  containers:
  -  name: python-requests-autogen
     image: docker.io/stevelsplunk/sfx-python:latest
     env:
     - name: SIGNALFX_SERVICE_NAME
       value: k8s-python-requests-trace-generator
     - name: MY_NODE_NAME
       valueFrom:
         fieldRef:
           apiVersion: v1
           fieldPath: spec.nodeName
     - name: SIGNALFX_ENDPOINT_URL
       value: http://$(MY_NODE_NAME):9080/v1/trace
     command: ["/bin/sh"]
     args: ["run-autogen.sh"]
     imagePullPolicy: Always
  restartPolicy: Always
