apiVersion: v1
kind: Pod
metadata:
  name: client-py-otel-k8s
  labels:
    app: client-py-otel-k8s
spec:
  containers:
  -  name: client-py-otel-k8s
     image: docker.io/stevelsplunk/splk-python:latest
     env:
     - name: SPLUNK_SERVICE_NAME
       value: client-py-otel-k8s
     - name: MY_NODE_NAME
       valueFrom:
         fieldRef:
           apiVersion: v1
           fieldPath: spec.nodeName
     - name: SPLUNK_TRACE_EXPORTER_URL
       value: http://$(MY_NODE_NAME):9080/v1/trace
     command: ["/bin/sh"]
     args: ["run-client-k8s-otel.sh"]
     imagePullPolicy: Always
  restartPolicy: Always
