signalFxAccessToken: YOURTOKENHERE
signalFxRealm: YOURREALMHERE
agentVersion: AGENTVERSIONHERE
clusterName: YOURCLUSTERNAMEHERE
# for otel-collector
# ingestUrl: http://otel-collector:9943
# traceEndpointUrl: http://otel-collector:7276/v2/trace
ingestUrl: https://ingest.YOURREALMHERE.signalfx.com
traceEndpointUrl: https://ingest.YOURREALMHERE.signalfx.com/v2/trace

monitors:
  - type: collectd/genericjmx
    host: client-java-otel-k8s
    port: 3000
  - type: signalfx-forwarder
    listenAddress: 0.0.0.0:9080
    defaultSpanTags:
# Customize this name to create your own APM environment
     environment: "sfx-workshop"

kubeletAPI.url: https://localhost:10250
writer:
  traceExportFormat: sapm
