apiVersion: v1
kind: Pod
metadata:
  name: py-autogen
spec:
  containers:
  - name: py-autogen
    image: docker.io/stevelsplunk/splk-python-autogen
    ports:
    - containerPort: 6379
    env:
    - name: TZ
      value: America/New_York
    - name: REDISHOST
      value: 127.0.0.1
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=otel-demo
    - name: SPLUNK_SERVICE_NAME
      value: python-autogen-otel
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
    command: ["/bin/sh"]
    args: ["run-autogen.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: py-autogen
  labels:
    app: py-autogen
spec:
  selector:
    app: py-autogen
  ports:
  - port: 6379
    targetPort: 6379