apiVersion: v1
kind: Service
metadata:
  name: py-autogen
spec:
  type: ClusterIP
  selector:
    app: py-autogen
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: py-autogen
spec:
  containers:
  - name: py-autogen
    image: docker.io/stevelsplunk/splk-python-autogen
    ports:
    - containerPort: 6379
    env:
    - name: TZ
      value: America/New_York
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: environment=otel-demo
    - name: SPLUNK_SERVICE_NAME
      value: python-autogen-otel
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(MY_NODE_NAME):9080/v1/trace
    command: ["/bin/sh"]
    args: ["run-autogen.sh"]
    imagePullPolicy: Always