apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client-otel
spec:
  selector:
    matchLabels:
      name: java-client-otel
  template:
    metadata:
      labels:
        name: java-client-otel
    spec:
      containers:
        - name: java-client-otel
          image: 'docker.io/stevelsplunk/splk-java:latest'
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: OTEL_EXPORTER_JAEGER_SERVICE_NAME
              value: java-client-otel
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://$(MY_NODE_NAME):9080/v1/trace
          command:
            - /bin/sh
          args:
            - ./run-java-local-flask-jmx.sh
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: java-client-otel
spec:
  selector:
    name: java-client-otel
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
