apiVersion: v1
kind: Pod
metadata:
  name: client-java-otel-k8s
spec:
  containers:
  - name: client-java-otel-k8s
    image: docker.io/stevelsplunk/splk-java
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: 'service.name=client-java-otel-k8s,deployment.environment:apm-workshop'
    command: ["/bin/sh"]
    args: ["run-client.sh"]