apiVersion: v1
kind: Pod
metadata:
  name: pod-redis
spec:
  containers:
  - name: redis
    image: docker.io/stevelsplunk/redis:latest
    ports:
    - containerPort: 6379
    env:
    - name: TZ
      value: America/New_York
 
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: svc-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379