apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: stevelsplunk/redis
    env:
    - name: TZ
      value: America/New_York
    ports:
    - containerPort: 6379
    command: ["redis-server"]
#    args: ["/etc/redis/redis.conf"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379