---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    extensions:
      health_check:
      http_forwarder:
        egress:
          endpoint: "https://api.${SFX_REALM}.signalfx.com"
      zpages:
    receivers:
      sapm:
      signalfx:
      # This section is used to collect OpenTelemetry metrics
      # Even if just a SignalFx µAPM customer, these metrics are included
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['localhost:8888']
                  # If you want to use the environment filter
                  # In the SignalFx dashboard
                  #labels:
                    #environment: demo
              metric_relabel_configs:
                - source_labels: [ __name__ ]
                  regex: '.*grpc_io.*'
                  action: drop
      zipkin:
    processors:
      batch:
      memory_limiter:
        ballast_size_mib: 683
        check_interval: 2s
        limit_mib: 1800
        spike_limit_mib: 500
    exporters:
      # Traces
      sapm:
        access_token: "${SFX_TOKEN}"
        endpoint: "https://ingest.${SFX_REALM}.signalfx.com/v2/trace"
      # Metrics
      signalfx:
        access_token: "${SFX_TOKEN}"
        realm: "${SFX_REALM}"
    service:
      extensions: [health_check, http_forwarder, zpages]
      pipelines:
        traces:
          receivers: [sapm, zipkin]
          processors: [memory_limiter, batch]
          exporters: [sapm]
        metrics:
          receivers: [signalfx, prometheus]
          processors: [memory_limiter, batch]
          exporters: [signalfx]
        logs:
          receivers: [signalfx]
          processors: [memory_limiter, batch]
          exporters: [signalfx]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: sapm # Default endpoint for SignalFx APM receiver.
    port: 7276
  - name: zipkin # Default endpoint for Zipkin trace receiver.
    port: 9411
  - name: signalfx # Default endpoint for SignalFx metrics receiver.
    port: 9943
  - name: metrics # Default endpoint for the Collector metrics.
    port: 8888
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector-contrib:0.18.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        env:
        - name: SFX_REALM
          value: us1
        - name: SFX_TOKEN
          value: iggr1oMNzzoIbvsfjGq90Q
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 55680 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 6060  # Default endpoint for HTTP Forwarder extension.
        - containerPort: 7276  # Default endpoint for SignalFx APM receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 9411  # Default endpoint for Zipkin trace receiver.
        - containerPort: 9943  # Default endpoint for SignalFx metrics receiver.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
