clusterName: YOURCLUSTERHERE
splunkRealm: YOUREREALMHERE
splunkAccessToken: YOURTOKENHERE

otelAgent:
  config:
    receivers:
      signalfx:
        endpoint: 0.0.0.0:9943
    service:
      pipelines:
        metrics:
          receivers:
          - hostmetrics
          - kubeletstats
          - receiver_creator
          - signalfx