clusterName: sl-cluster
splunkRealm: us1
splunkAccessToken: F9D-tA0fv4_2a4PD7Zn0UQ

otelAgent:
  config:
    receivers:
      smartagent/redis:    
        type: collectd/redis
        host: redis
        port: 6379
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - smartagent/redis