clusterName: YOURCLUSTERNAMEHERE
splunkRealm: YOURREALMHERE
splunkAccessToken: YOURTOKENNAMEHERE

otelAgent:
  config:
    processors:
      attributes/update:
        actions:
          - key: user.id
            value: redacted
            action: update
    service:
      pipelines:
        traces:
          processors: [memory_limiter, k8s_tagger, batch, resource, resourcedetection, attributes/update]